#!/bin/sh

APP_PATH=`echo $0 | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+1] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'`
APP_PATH=`cd "$APP_PATH"; pwd`

# See if there is a cached version of TL available
export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
if ! command -v lualatex > /dev/null; then
  # Obtain TeX Live
  wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  tar -xzf install-tl-unx.tar.gz
  cd install-tl-20*

  echo "Installing using profile:"
  cat ${APP_PATH}/texlive.profile

  echo

  # Install a minimal system
  ./install-tl --profile="${APP_PATH}/texlive.profile"

  cd ..

  # Keep no backups (not required, simply makes cache bigger)
  tlmgr option -- autobackup 0

  # Other contrib packages: done as a block to avoid multiple calls to tlmgr
  # texlive-latex-base is needed to run pdflatex
  tlmgr install   \
    12many    /
    2up    /
    Asana-Math    /
    ESIEEcv    /
    FAQ-en    /
    GS1    /
    HA-prosper    /
    IEEEconf    /
    IEEEtran    /
    MemoirChapStyles    /
    SIstyle    /
    SIunits    /
    Tabbing    /
    Type1fonts    /
    a0poster    /
    a2ping    /
    a2ping.x86_64-linux    /
    a4wide    /
    a5comb    /
    aastex    /
    abbr    /
    abc    /
    abntex2    /
    abraces    /
    abstract    /
    abstyles    /
    academicons    /
    accanthis    /
    accfonts    /
    accfonts.x86_64-linux    /
    achemso    /
    acmart    /
    acmconf    /
    acro    /
    acronym    /
    acroterm    /
    active-conf    /
    actuarialangle    /
    addfont    /
    addlines    /
    adfathesis    /
    adforn    /
    adfsymbols    /
    adhocfilelist    /
    adhocfilelist.x86_64-linux    /
    adjmulticol    /
    adjustbox    /
    adobemapping    /
    adrconv    /
    adtrees    /
    advdate    /
    ae    /
    aecc    /
    aeguill    /
    afm2pl    /
    afm2pl.x86_64-linux    /
    afparticle    /
    afthesis    /
    aguplus    /
    aiaa    /
    aichej    /
    ajl    /
    akktex    /
    akletter    /
    alegreya    /
    aleph    /
    aleph.x86_64-linux    /
    alertmessage    /
    alg    /
    algorithm2e    /
    algorithmicx    /
    algorithms    /
    allrunes    /
    almfixed    /
    alnumsec    /
    alterqcm    /
    altfont    /
    ametsoc    /
    amiri    /
    amsaddr    /
    amscls    /
    amsfonts    /
    amslatex-primer    /
    amsldoc-it    /
    amsldoc-vn    /
    amsmath    /
    amsmath-it    /
    amsrefs    /
    amstex    /
    amstex.x86_64-linux    /
    amsthdoc-it    /
    animate    /
    anonchap    /
    anonymouspro    /
    answers    /
    antiqua    /
    antomega    /
    antt    /
    anufinalexam    /
    anyfontsize    /
    anysize    /
    aobs-tikz    /
    aomart    /
    apa    /
    apa6    /
    apa6e    /
    apacite    /
    apalike-german    /
    apalike2    /
    apnum    /
    appendix    /
    appendixnumberbeamer    /
    apprends-latex    /
    apptools    /
    apxproof    /
    arabi    /
    arabi-add    /
    arabluatex    /
    arabtex    /
    arabxetex    /
    aramaic-serto    /
    arara    /
    arara.x86_64-linux    /
    archaeologie    /
    archaic    /
    arcs    /
    arev    /
    arimo    /
    armtex    /
    around-the-bend    /
    arphic    /
    arphic-ttf    /
    arrayjobx    /
    arraysort    /
    arsclassica    /
    articleingud    /
    arydshln    /
    asaetr    /
    asapsym    /
    ascelike    /
    ascii-chart    /
    ascii-font    /
    asciilist    /
    askmaps    /
    aspectratio    /
    assignment    /
    assoccnt    /
    astro    /
    asyfig    /
    asymptote    /
    asymptote-by-example-zh-cn    /
    asymptote-faq-zh-cn    /
    asymptote-manual-zh-cn    /
    asymptote.x86_64-linux    /
    asypictureb    /
    attachfile    /
    aucklandthesis    /
    augie    /
    auncial-new    /
    aurical    /
    aurl    /
    authoraftertitle    /
    authorindex    /
    authorindex.x86_64-linux    /
    auto-pst-pdf    /
    autoaligne    /
    autoarea    /
    autobreak    /
    automata    /
    autonum    /
    autopdf    /
    autosp    /
    autosp.x86_64-linux    /
    avantgar    /
    avremu    /
    awesomebox    /
    b1encoding    /
    babel    /
    babel-albanian    /
    babel-bahasa    /
    babel-basque    /
    babel-belarusian    /
    babel-bosnian    /
    babel-breton    /
    babel-bulgarian    /
    babel-catalan    /
    babel-croatian    /
    babel-czech    /
    babel-danish    /
    babel-dutch    /
    babel-english    /
    babel-esperanto    /
    babel-estonian    /
    babel-finnish    /
    babel-french    /
    babel-friulan    /
    babel-galician    /
    babel-georgian    /
    babel-german    /
    babel-greek    /
    babel-hebrew    /
    babel-hungarian    /
    babel-icelandic    /
    babel-interlingua    /
    babel-irish    /
    babel-italian    /
    babel-japanese    /
    babel-kurmanji    /
    babel-latin    /
    babel-latvian    /
    babel-macedonian    /
    babel-norsk    /
    babel-occitan    /
    babel-piedmontese    /
    babel-polish    /
    babel-portuges    /
    babel-romanian    /
    babel-romansh    /
    babel-russian    /
    babel-samin    /
    babel-scottish    /
    babel-serbian    /
    babel-serbianc    /
    babel-slovak    /
    babel-slovenian    /
    babel-sorbian    /
    babel-spanglish    /
    babel-spanish    /
    babel-swedish    /
    babel-thai    /
    babel-turkish    /
    babel-ukrainian    /
    babel-vietnamese    /
    babel-welsh    /
    babelbib    /
    background    /
    backnaur    /
    baekmuk    /
    bagpipe    /
    bangorcsthesis    /
    bangorexam    /
    bangtex    /
    bankstatement    /
    barcodes    /
    bardiag    /
    barr    /
    bartel-chess-fonts    /
    bashful    /
    basicarith    /
    baskervald    /
    baskervaldx    /
    baskervillef    /
    basque-book    /
    basque-date    /
    bbcard    /
    bbding    /
    bbm    /
    bbm-macros    /
    bbold    /
    bbold-type1    /
    bchart    /
    bclogo    /
    beamer    /
    beamer-FUBerlin    /
    beamer-tut-pt    /
    beamer-verona    /
    beamer2thesis    /
    beameraudience    /
    beamercolorthemeowl    /
    beamerdarkthemes    /
    beamerposter    /
    beamersubframe    /
    beamerswitch    /
    beamertheme-cuerna    /
    beamertheme-detlevcm    /
    beamertheme-epyt    /
    beamertheme-metropolis    /
    beamertheme-phnompenh    /
    beamertheme-upenn-bc    /
    beamerthemejltree    /
    beamerthemenirma    /
    beebe    /
    begingreek    /
    begriff    /
    belleek    /
    bengali    /
    bera    /
    berenisadf    /
    besjournals    /
    bestpapers    /
    betababel    /
    beton    /
    beuron    /
    bewerbung    /
    bez123    /
    bezos    /
    bgreek    /
    bgteubner    /
    bguq    /
    bhcexam    /
    bib-fr    /
    bibarts    /
    biber    /
    biber.x86_64-linux    /
    bibexport    /
    bibexport.x86_64-linux    /
    bibhtml    /
    biblatex    /
    biblatex-abnt    /
    biblatex-anonymous    /
    biblatex-apa    /
    biblatex-bookinarticle    /
    biblatex-bookinother    /
    biblatex-bwl    /
    biblatex-caspervector    /
    biblatex-chem    /
    biblatex-chicago    /
    biblatex-claves    /
    biblatex-dw    /
    biblatex-fiwi    /
    biblatex-gb7714-2015    /
    biblatex-gost    /
    biblatex-historian    /
    biblatex-ieee    /
    biblatex-ijsra    /
    biblatex-iso690    /
    biblatex-juradiss    /
    biblatex-lni    /
    biblatex-luh-ipw    /
    biblatex-manuscripts-philology    /
    biblatex-mla    /
    biblatex-morenames    /
    biblatex-multiple-dm    /
    biblatex-musuos    /
    biblatex-nature    /
    biblatex-nejm    /
    biblatex-nottsclassic    /
    biblatex-opcit-booktitle    /
    biblatex-philosophy    /
    biblatex-phys    /
    biblatex-publist    /
    biblatex-realauthor    /
    biblatex-sbl    /
    biblatex-science    /
    biblatex-source-division    /
    biblatex-subseries    /
    biblatex-swiss-legal    /
    biblatex-trad    /
    biblatex-true-citepages-omit    /
    bibleref    /
    bibleref-french    /
    bibleref-german    /
    bibleref-lds    /
    bibleref-mouth    /
    bibleref-parse    /
    bibletext    /
    biblist    /
    bibtex    /
    bibtex.x86_64-linux    /
    bibtex8    /
    bibtex8.x86_64-linux    /
    bibtexperllibs    /
    bibtexu    /
    bibtexu.x86_64-linux    /
    bibtopic    /
    bibtopicprefix    /
    bibunits    /
    bidi    /
    bidi-atbegshi    /
    bidicontour    /
    bidihl    /
    bidipagegrid    /
    bidipresentation    /
    bidishadowtext    /
    bigfoot    /
    bigints    /
    binarytree    /
    binomexp    /
    biocon    /
    biolett-bst    /
    bitelist    /
    bitpattern    /
    bizcard    /
    blacklettert1    /
    blindtext    /
    blkarray    /
    blochsphere    /
    block    /
    blockdraw_mp    /
    bloques    /
    blox    /
    bnumexpr    /
    bodegraph    /
    bohr    /
    boisik    /
    boites    /
    bold-extra    /
    boldtensors    /
    bondgraph    /
    bondgraphs    /
    bookcover    /
    bookdb    /
    bookest    /
    bookhands    /
    booklet    /
    bookman    /
    booktabs    /
    booktabs-de    /
    booktabs-fr    /
    boolexpr    /
    boondox    /
    bophook    /
    borceux    /
    bosisio    /
    boxedminipage    /
    boxedminipage2e    /
    boxhandler    /
    bpchem    /
    bpolynomial    /
    br-lex    /
    bracketkey    /
    braids    /
    braille    /
    braket    /
    brandeis-dissertation    /
    breakcites    /
    breakurl    /
    breqn    /
    bropd    /
    brushscr    /
    bullcntr    /
    bundledoc    /
    bundledoc.x86_64-linux    /
    burmese    /
    bussproofs    /
    bxbase    /
    bxcjkjatype    /
    bxdpx-beamer    /
    bxdvidriver    /
    bxeepic    /
    bxenclose    /
    bxjalipsum    /
    bxjscls    /
    bxnewfont    /
    bxpapersize    /
    bxpdfver    /
    bytefield    /
    c-pascal    /
    c90    /
    cabin    /
    cachepic    /
    cachepic.x86_64-linux    /
    caladea    /
    calcage    /
    calctab    /
    calculation    /
    calculator    /
    calligra    /
    calligra-type1    /
    calrsfs    /
    cals    /
    calxxxx-yyyy    /
    cancel    /
    canoniclayout    /
    cantarell    /
    capt-of    /
    captcont    /
    captdef    /
    caption    /
    carbohydrates    /
    carlisle    /
    carlito    /
    carolmin-ps    /
    cascadilla    /
    cases    /
    casyl    /
    catchfilebetweentags    /
    catcodes    /
    catechis    /
    catoptions    /
    cbcoptic    /
    cbfonts    /
    cbfonts-fd    /
    cc-pl    /
    ccaption    /
    ccfonts    /
    ccicons    /
    cclicenses    /
    cd    /
    cd-cover    /
    cdpbundl    /
    cell    /
    cellspace    /
    celtic    /
    censor    /
    cfr-initials    /
    cfr-lm    /
    changebar    /
    changelayout    /
    changepage    /
    changes    /
    chappg    /
    chapterfolder    /
    charter    /
    chbibref    /
    checkcites    /
    checkcites.x86_64-linux    /
    checklistings    /
    checklistings.x86_64-linux    /
    chem-journal    /
    chemarrow    /
    chembst    /
    chemcompounds    /
    chemcono    /
    chemexec    /
    chemfig    /
    chemformula    /
    chemgreek    /
    chemmacros    /
    chemnum    /
    chemschemex    /
    chemstyle    /
    cherokee    /
    chess    /
    chess-problem-diagrams    /
    chessboard    /
    chessfss    /
    chet    /
    chextras    /
    chicago    /
    chicago-annote    /
    chickenize    /
    chivo    /
    chkfloat    /
    chktex    /
    chktex.x86_64-linux    /
    chletter    /
    chngcntr    /
    chronology    /
    chronosys    /
    chscite    /
    churchslavonic    /
    cinzel    /
    circ    /
    circuitikz    /
    cite    /
    citeall    /
    cjhebrew    /
    cjk    /
    cjk-gs-integrate    /
    cjk-gs-integrate.x86_64-linux    /
    cjk-ko    /
    cjkpunct    /
    cjkutils    /
    cjkutils.x86_64-linux    /
    classics    /
    classicthesis    /
    classpack    /
    cleanthesis    /
    clearsans    /
    clefval    /
    cleveref    /
    clipboard    /
    clock    /
    cloze    /
    clrscode    /
    clrscode3e    /
    cm    /
    cm-lgc    /
    cm-super    /
    cm-unicode    /
    cmap    /
    cmarrows    /
    cmbright    /
    cmcyr    /
    cmdstring    /
    cmdtrack    /
    cmexb    /
    cmextra    /
    cmll    /
    cmpica    /
    cmpj    /
    cmsd    /
    cmtiup    /
    cnbwp    /
    cnltx    /
    cns    /
    cntformats    /
    cntperchap    /
    cochineal    /
    codedoc    /
    codepage    /
    codesection    /
    codicefiscaleitaliano    /
    collcell    /
    collectbox    /
    collection-basic    /
    collection-bibtexextra    /
    collection-binextra    /
    collection-context    /
    collection-fontsextra    /
    collection-fontsrecommended    /
    collection-fontutils    /
    collection-formatsextra    /
    collection-games    /
    collection-genericextra    /
    collection-genericrecommended    /
    collection-htmlxml    /
    collection-humanities    /
    collection-langafrican    /
    collection-langarabic    /
    collection-langchinese    /
    collection-langcjk    /
    collection-langcyrillic    /
    collection-langczechslovak    /
    collection-langenglish    /
    collection-langeuropean    /
    collection-langfrench    /
    collection-langgerman    /
    collection-langgreek    /
    collection-langindic    /
    collection-langitalian    /
    collection-langjapanese    /
    collection-langkorean    /
    collection-langother    /
    collection-langpolish    /
    collection-langportuguese    /
    collection-langspanish    /
    collection-latex    /
    collection-latexextra    /
    collection-latexrecommended    /
    collection-luatex    /
    collection-mathscience    /
    collection-metapost    /
    collection-music    /
    collection-omega    /
    collection-pictures    /
    collection-plainextra    /
    collection-pstricks    /
    collection-publishers    /
    collection-texworks    /
    collection-xetex    /
    collref    /
    colordoc    /
    colorinfo    /
    coloring    /
    colorsep    /
    colorspace    /
    colortab    /
    colortbl    /
    colorwav    /
    colorweb    /
    colourchange    /
    combelow    /
    combine    /
    combinedgraphics    /
    comfortaa    /
    comicneue    /
    comma    /
    commado    /
    commath    /
    comment    /
    compactbib    /
    complexity    /
    components-of-TeX    /
    comprehensive    /
    computational-complexity    /
    concepts    /
    concmath    /
    concmath-fonts    /
    concprog    /
    concrete    /
    confproc    /
    constants    /
    conteq    /
    context    /
    context-account    /
    context-algorithmic    /
    context-animation    /
    context-annotation    /
    context-bnf    /
    context-chromato    /
    context-cmscbf    /
    context-cmttbf    /
    context-construction-plan    /
    context-cyrillicnumbers    /
    context-degrade    /
    context-fancybreak    /
    context-filter    /
    context-french    /
    context-fullpage    /
    context-gantt    /
    context-gnuplot    /
    context-inifile    /
    context-layout    /
    context-letter    /
    context-lettrine    /
    context-mathsets    /
    context-notes-zh-cn    /
    context-rst    /
    context-ruby    /
    context-simplefonts    /
    context-simpleslides    /
    context-title    /
    context-transliterator    /
    context-typearea    /
    context-typescripts    /
    context-vim    /
    context-visualcounter    /
    context.x86_64-linux    /
    continue    /
    contour    /
    contracard    /
    conv-xkv    /
    convbkmk    /
    convbkmk.x86_64-linux    /
    cooking    /
    cooking-units    /
    cookingsymbols    /
    cool    /
    coollist    /
    coolstr    /
    coolthms    /
    cooltooltips    /
    coordsys    /
    copyedit    /
    copyrightbox    /
    cormorantgaramond    /
    coseoul    /
    countriesofeurope    /
    counttexruns    /
    courier    /
    courier-scaled    /
    courseoutline    /
    coursepaper    /
    coverpage    /
    covington    /
    cprotect    /
    cquthesis    /
    crbox    /
    crimson    /
    crop    /
    crossreference    /
    crossrefware    /
    crossrefware.x86_64-linux    /
    crossword    /
    crosswrd    /
    cryptocode    /
    cryst    /
    cs    /
    csbulletin    /
    cslatex    /
    cslatex.x86_64-linux    /
    csplain    /
    csplain.x86_64-linux    /
    csquotes    /
    csquotes-de    /
    css-colors    /
    cstex    /
    cstypo    /
    csvsimple    /
    ctable    /
    ctablestack    /
    ctan_chk    /
    ctanify    /
    ctanify.x86_64-linux    /
    ctanupload    /
    ctanupload.x86_64-linux    /
    ctex    /
    ctex-faq    /
    ctib    /
    ctie    /
    ctie.x86_64-linux    /
    cuisine    /
    currfile    /
    currvita    /
    cursolatex    /
    curve    /
    curve2e    /
    curves    /
    custom-bib    /
    cutwin    /
    cv    /
    cv4tw    /
    cweb    /
    cweb-latex    /
    cweb.x86_64-linux    /
    cyber    /
    cybercic    /
    cyklop    /
    cyrillic    /
    cyrillic-bin    /
    cyrillic-bin.x86_64-linux    /
    cyrplain    /
    dad    /
    dancers    /
    dantelogo    /
    dashbox    /
    dashrule    /
    dashundergaps    /
    dataref    /
    datatool    /
    dateiliste    /
    datenumber    /
    datetime    /
    datetime2    /
    datetime2-bahasai    /
    datetime2-basque    /
    datetime2-breton    /
    datetime2-bulgarian    /
    datetime2-catalan    /
    datetime2-croatian    /
    datetime2-czech    /
    datetime2-danish    /
    datetime2-dutch    /
    datetime2-en-fulltext    /
    datetime2-english    /
    datetime2-esperanto    /
    datetime2-estonian    /
    datetime2-finnish    /
    datetime2-french    /
    datetime2-galician    /
    datetime2-german    /
    datetime2-greek    /
    datetime2-hebrew    /
    datetime2-icelandic    /
    datetime2-irish    /
    datetime2-it-fulltext    /
    datetime2-italian    /
    datetime2-latin    /
    datetime2-lsorbian    /
    datetime2-magyar    /
    datetime2-norsk    /
    datetime2-polish    /
    datetime2-portuges    /
    datetime2-romanian    /
    datetime2-russian    /
    datetime2-samin    /
    datetime2-scottish    /
    datetime2-serbian    /
    datetime2-slovak    /
    datetime2-slovene    /
    datetime2-spanish    /
    datetime2-swedish    /
    datetime2-turkish    /
    datetime2-ukrainian    /
    datetime2-usorbian    /
    datetime2-welsh    /
    dblfloatfix    /
    dccpaper    /
    dcpic    /
    de-macro    /
    de-macro.x86_64-linux    /
    decimal    /
    decorule    /
    dehyph-exptl    /
    dejavu    /
    delim    /
    delimseasy    /
    delimset    /
    delimtxt    /
    denisbdoc    /
    detex    /
    detex.x86_64-linux    /
    dhua    /
    diadia    /
    diadia.x86_64-linux    /
    diagbox    /
    diagmac2    /
    diagnose    /
    dialogl    /
    dice    /
    dichokey    /
    dickimaw    /
    dictsym    /
    diffcoeff    /
    digiconfigs    /
    din1505    /
    dinat    /
    dinbrief    /
    dingbat    /
    directory    /
    dirtree    /
    dirtytalk    /
    disser    /
    dithesis    /
    dk-bib    /
    dlfltxb    /
    dnaseq    /
    dnp    /
    doc-pictex    /
    docbytex    /
    doclicense    /
    docmfp    /
    docmute    /
    doctools    /
    documentation    /
    doi    /
    doipubmed    /
    dosepsbin    /
    dosepsbin.x86_64-linux    /
    dot2texi    /
    dotarrow    /
    dotseqn    /
    dottex    /
    doublestroke    /
    dowith    /
    download    /
    dox    /
    dozenal    /
    dpfloat    /
    dprogress    /
    drac    /
    draftcopy    /
    draftwatermark    /
    dramatist    /
    dratex    /
    drawmatrix    /
    drawstack    /
    drm    /
    droid    /
    droit-fr    /
    drs    /
    drv    /
    dsptricks    /
    dtk    /
    dtl    /
    dtl.x86_64-linux    /
    dtxdescribe    /
    dtxgallery    /
    dtxgen    /
    dtxgen.x86_64-linux    /
    dtxtut    /
    duerer    /
    duerer-latex    /
    duotenzor    /
    dutchcal    /
    dvdcoll    /
    dvgloss    /
    dvi2tty    /
    dvi2tty.x86_64-linux    /
    dviasm    /
    dviasm.x86_64-linux    /
    dvicopy    /
    dvicopy.x86_64-linux    /
    dvidvi    /
    dvidvi.x86_64-linux    /
    dviincl    /
    dviljk    /
    dviljk.x86_64-linux    /
    dvipdfmx    /
    dvipdfmx.x86_64-linux    /
    dvipng    /
    dvipng.x86_64-linux    /
    dvipos    /
    dvipos.x86_64-linux    /
    dvips    /
    dvips.x86_64-linux    /
    dvipsconfig    /
    dvisvgm    /
    dvisvgm.x86_64-linux    /
    dynamicnumber    /
    dynblocks    /
    dyntree    /
    e-french    /
    ean    /
    ean13isbn    /
    easy    /
    easy-todo    /
    easyfig    /
    easylist    /
    easyreview    /
    ebezier    /
    ebgaramond    /
    ebgaramond-maths    /
    ebong    /
    ebong.x86_64-linux    /
    ebook    /
    ebproof    /
    ebsthesis    /
    ec    /
    ecc    /
    ecclesiastic    /
    ecgdraw    /
    ecltree    /
    eco    /
    ecobiblatex    /
    econometrics    /
    economic    /
    ecv    /
    ed    /
    edfnotes    /
    edmac    /
    edmargin    /
    ednotes    /
    eemeir    /
    eepic    /
    efbox    /
    egameps    /
    egplot    /
    eiad    /
    eiad-ltx    /
    eijkhout    /
    einfuehrung    /
    einfuehrung2    /
    ejpecp    /
    ekaia    /
    elbioimp    /
    electrum    /
    eledform    /
    eledmac    /
    elements    /
    ellipse    /
    ellipsis    /
    elmath    /
    elocalloc    /
    elpres    /
    elsarticle    /
    elteikthesis    /
    eltex    /
    elvish    /
    elzcards    /
    emarks    /
    embedall    /
    embrac    /
    emf    /
    emisa    /
    emp    /
    emptypage    /
    emulateapj    /
    enctex    /
    encxvlna    /
    endfloat    /
    endheads    /
    endiagram    /
    endnotes    /
    engpron    /
    engrec    /
    engtlc    /
    enigma    /
    enotez    /
    enumitem    /
    enumitem-zref    /
    envbig    /
    environ    /
    envlab    /
    epigrafica    /
    epigram    /
    epigraph    /
    epiolmec    /
    eplain    /
    eplain.x86_64-linux    /
    epsdice    /
    epsf    /
    epsf-dvipdfmx    /
    epsincl    /
    epslatex-fr    /
    epspdf    /
    epspdf.x86_64-linux    /
    epspdfconversion    /
    epstopdf    /
    epstopdf.x86_64-linux    /
    eqell    /
    eqlist    /
    eqname    /
    eqnarray    /
    eqparbox    /
    erdc    /
    erewhon    /
    errata    /
    es-tex-faq    /
    esami    /
    esdiff    /
    esint    /
    esint-type1    /
    esk    /
    eskd    /
    eskdx    /
    eso-pic    /
    esrelation    /
    esstix    /
    estcpmm    /
    esvect    /
    etaremune    /
    etdipa    /
    etex    /
    etex-pkg    /
    etextools    /
    ethiop    /
    ethiop-t1    /
    etoc    /
    etoolbox    /
    etoolbox-de    /
    euenc    /
    eukdate    /
    euler    /
    eulerpx    /
    eulervm    /
    euro    /
    euro-ce    /
    europasscv    /
    europecv    /
    eurosym    /
    euxm    /
    everyhook    /
    everypage    /
    exam    /
    exam-n    /
    examdesign    /
    example    /
    examplep    /
    exceltex    /
    exceltex.x86_64-linux    /
    excludeonly    /
    exercise    /
    exercises    /
    exp-testopt    /
    expdlist    /
    expex    /
    export    /
    expressg    /
    exsheets    /
    exsol    /
    extarrows    /
    exteps    /
    extpfeil    /
    extract    /
    extsizes    /
    facsimile    /
    factura    /
    facture    /
    faktor    /
    fancybox    /
    fancyhdr    /
    fancyhdr-it    /
    fancylabel    /
    fancynum    /
    fancypar    /
    fancyref    /
    fancyslides    /
    fancytabs    /
    fancytooltips    /
    fancyvrb    /
    fandol    /
    fast-diagram    /
    fbb    /
    fbithesis    /
    fbs    /
    fc    /
    fcavtex    /
    fcltxdoc    /
    fcolumn    /
    fdsymbol    /
    featpost    /
    fei    /
    fenixpar    /
    fetamont    /
    feupphdteses    /
    feyn    /
    feynmf    /
    feynmp-auto    /
    ffslides    /
    fge    /
    fgruler    /
    fibeamer    /
    fifinddo-info    /
    fifo-stack    /
    fig4latex    /
    fig4latex.x86_64-linux    /
    figbas    /
    figbib    /
    figflow    /
    figsize    /
    filecontents    /
    filecontentsdef    /
    filedate    /
    filehook    /
    fileinfo    /
    filemod    /
    finbib    /
    findhyph    /
    findhyph.x86_64-linux    /
    fink    /
    finstrut    /
    fira    /
    first-latex-doc    /
    fitbox    /
    fithesis    /
    fix2col    /
    fixcmex    /
    fixfoot    /
    fixlatvian    /
    fixltxhyph    /
    fixme    /
    fixmetodonotes    /
    fixpdfmag    /
    fjodor    /
    flabels    /
    flacards    /
    flagderiv    /
    flashcards    /
    flashmovie    /
    flipbook    /
    flippdf    /
    float    /
    floatflt    /
    floatrow    /
    flowchart    /
    flowfram    /
    fltpoint    /
    fmp    /
    fmtcount    /
    fn2end    /
    fnbreak    /
    fncychap    /
    fncylab    /
    fnpara    /
    fnpct    /
    fntproof    /
    fnumprint    /
    foekfont    /
    foilhtml    /
    fonetika    /
    font-change    /
    font-change-xetex    /
    fontawesome    /
    fontaxes    /
    fontbook    /
    fontch    /
    fontinst    /
    fontinst.x86_64-linux    /
    fontmfizz    /
    fontname    /
    fontools    /
    fontools.x86_64-linux    /
    fonts-churchslavonic    /
    fonts-tlwg    /
    fontspec    /
    fonttable    /
    fontware    /
    fontware.x86_64-linux    /
    fontwrap    /
    footbib    /
    footmisc    /
    footmisx    /
    footnotebackref    /
    footnotehyper    /
    footnoterange    /
    footnpag    /
    forarray    /
    foreign    /
    forest    /
    forest-quickstart    /
    forloop    /
    formation-latex-ul    /
    formlett    /
    formular    /
    fouridx    /
    fourier    /
    fouriernc    /
    fp    /
    fpl    /
    fragmaster    /
    fragmaster.x86_64-linux    /
    fragments    /
    frame    /
    framed    /
    francais-bst    /
    frankenstein    /
    frcursive    /
    frederika2016    /
    frege    /
    frletter    /
    frontespizio    /
    ftcap    /
    ftnxtra    /
    fullblck    /
    fullminipage    /
    fullwidth    /
    functan    /
    fundus-calligra    /
    fundus-cyr    /
    fundus-sueterlin    /
    fvextra    /
    fwlw    /
    g-brief    /
    gaceta    /
    galois    /
    gamebook    /
    garrigues    /
    garuda-c90    /
    gastex    /
    gatech-thesis    /
    gates    /
    gauss    /
    gb4e    /
    gcard    /
    gchords    /
    gcite    /
    gender    /
    gene-logic    /
    genealogy    /
    genealogytree    /
    genmisc    /
    genmpage    /
    gentium-tug    /
    gentle    /
    geometry    /
    geometry-de    /
    german    /
    germbib    /
    germkorr    /
    geschichtsfrkl    /
    getfiledate    /
    getitems    /
    getmap    /
    getmap.x86_64-linux    /
    getoptk    /
    gfnotation    /
    gfsartemisia    /
    gfsbaskerville    /
    gfsbodoni    /
    gfscomplutum    /
    gfsdidot    /
    gfsneohellenic    /
    gfsporson    /
    gfssolomos    /
    ghab    /
    ghsystem    /
    gillcm    /
    gillius    /
    gincltex    /
    ginpenc    /
    gitfile-info    /
    gitinfo    /
    gitinfo2    /
    gitlog    /
    gloss    /
    gloss-occitan    /
    glossaries    /
    glossaries-danish    /
    glossaries-dutch    /
    glossaries-english    /
    glossaries-extra    /
    glossaries-french    /
    glossaries-german    /
    glossaries-irish    /
    glossaries-italian    /
    glossaries-magyar    /
    glossaries-polish    /
    glossaries-portuges    /
    glossaries-serbian    /
    glossaries-spanish    /
    glossaries.x86_64-linux    /
    glyphlist    /
    gmdoc    /
    gmdoc-enhance    /
    gmiflink    /
    gmp    /
    gmutils    /
    gmverb    /
    gmverse    /
    gnu-freefont    /
    gnuplottex    /
    go    /
    gobble    /
    gofonts    /
    gost    /
    gothic    /
    gradientframe    /
    gradstudentresume    /
    grafcet    /
    grant    /
    graphbox    /
    graphics    /
    graphics-cfg    /
    graphics-def    /
    graphics-pln    /
    graphicx-psmin    /
    graphicxbox    /
    graphviz    /
    greek-fontenc    /
    greek-inputenc    /
    greekdates    /
    greektex    /
    greektonoi    /
    greenpoint    /
    gregoriotex    /
    gregoriotex.x86_64-linux    /
    grfpaste    /
    grid    /
    grid-system    /
    gridset    /
    grotesq    /
    grundgesetze    /
    gsemthesis    /
    gsftopk    /
    gsftopk.x86_64-linux    /
    gtl    /
    gtrcrd    /
    gu    /
    guide-to-latex    /
    guitar    /
    guitarchordschemes    /
    guitlogo    /
    gustlib    /
    gustprog    /
    gzt    /
    h2020proposal    /
    hacm    /
    halloweenmath    /
    handout    /
    hands    /
    hang    /
    hanging    /
    hanoi    /
    happy4th    /
    har2nat    /
    hardwrap    /
    harmony    /
    harnon-cv    /
    harpoon    /
    harvard    /
    harveyballs    /
    harvmac    /
    hatching    /
    hausarbeit-jura    /
    havannah    /
    hc    /
    he-she    /
    helvetic    /
    hep    /
    hepnames    /
    hepparticles    /
    hepthesis    /
    hepunits    /
    here    /
    heuristica    /
    hexgame    /
    hf-tikz    /
    hfbright    /
    hfoldsty    /
    hhtensor    /
    histogr    /
    historische-zeitschrift    /
    hitec    /
    hletter    /
    hobby    /
    hobete    /
    hook-pre-commit-pkg    /
    horoscop    /
    hpsdiss    /
    hrefhide    /
    hrlatex    /
    hustthesis    /
    hvfloat    /
    hvindex    /
    hypdvips    /
    hyper    /
    hypernat    /
    hyperref    /
    hyperref-docsrc    /
    hyperxmp    /
    hyph-utf8    /
    hyphen-afrikaans    /
    hyphen-ancientgreek    /
    hyphen-arabic    /
    hyphen-armenian    /
    hyphen-base    /
    hyphen-basque    /
    hyphen-bulgarian    /
    hyphen-catalan    /
    hyphen-chinese    /
    hyphen-churchslavonic    /
    hyphen-coptic    /
    hyphen-croatian    /
    hyphen-czech    /
    hyphen-danish    /
    hyphen-dutch    /
    hyphen-english    /
    hyphen-esperanto    /
    hyphen-estonian    /
    hyphen-ethiopic    /
    hyphen-farsi    /
    hyphen-finnish    /
    hyphen-french    /
    hyphen-friulan    /
    hyphen-galician    /
    hyphen-georgian    /
    hyphen-german    /
    hyphen-greek    /
    hyphen-hungarian    /
    hyphen-icelandic    /
    hyphen-indic    /
    hyphen-indonesian    /
    hyphen-interlingua    /
    hyphen-irish    /
    hyphen-italian    /
    hyphen-kurmanji    /
    hyphen-latin    /
    hyphen-latvian    /
    hyphen-lithuanian    /
    hyphen-mongolian    /
    hyphen-norwegian    /
    hyphen-occitan    /
    hyphen-piedmontese    /
    hyphen-polish    /
    hyphen-portuguese    /
    hyphen-romanian    /
    hyphen-romansh    /
    hyphen-russian    /
    hyphen-sanskrit    /
    hyphen-serbian    /
    hyphen-slovak    /
    hyphen-slovenian    /
    hyphen-spanish    /
    hyphen-swedish    /
    hyphen-thai    /
    hyphen-turkish    /
    hyphen-turkmen    /
    hyphen-ukrainian    /
    hyphen-uppersorbian    /
    hyphen-welsh    /
    hyphenat    /
    hyphenex    /
    hyplain    /
    ibycus-babel    /
    ibygrk    /
    icsv    /
    idxcmds    /
    idxlayout    /
    ieeepes    /
    ietfbibs    /
    ifetex    /
    iffont    /
    ifluatex    /
    ifmslide    /
    ifmtarg    /
    ifnextok    /
    ifoddpage    /
    ifplatform    /
    ifsym    /
    iftex    /
    ifthenx    /
    ifxetex    /
    iitem    /
    ijmart    /
    ijqc    /
    ijsra    /
    imac    /
    image-gallery    /
    imakeidx    /
    imfellenglish    /
    impatient    /
    impatient-cn    /
    impatient-fr    /
    impnattypo    /
    import    /
    imsproc    /
    imtekda    /
    incgraph    /
    inconsolata    /
    index    /
    indextools    /
    initials    /
    inlinebib    /
    inlinedef    /
    inputtrc    /
    insbox    /
    installfont    /
    installfont.x86_64-linux    /
    interactiveworkbook    /
    interchar    /
    interfaces    /
    interpreter    /
    interval    /
    intro-scientific    /
    inversepath    /
    invoice    /
    ionumbers    /
    iopart-num    /
    ipaex    /
    ipaex-type1    /
    iscram    /
    iso    /
    iso10303    /
    isodate    /
    isodoc    /
    isomath    /
    isonums    /
    isorot    /
    isotope    /
    issuulinks    /
    itnumpar    /
    iwhdp    /
    iwona    /
    jablantile    /
    jacow    /
    jadetex    /
    jadetex.x86_64-linux    /
    jamtimes    /
    japanese-otf    /
    japanese-otf-uptex    /
    jknapltx    /
    jlabels    /
    jmlr    /
    jmn    /
    jneurosci    /
    jpsj    /
    js-misc    /
    jsclasses    /
    jslectureplanner    /
    jumplines    /
    junicode    /
    jura    /
    juraabbrev    /
    jurabib    /
    juramisc    /
    jurarsp    /
    jvlisting    /
    kantlipsum    /
    karnaugh    /
    karnaugh-map    /
    karnaughmap    /
    kastrup    /
    kdgdocs    /
    kerkis    /
    kerntest    /
    keycommand    /
    keyfloat    /
    keyreader    /
    keystroke    /
    keyval2e    /
    keyvaltable    /
    kix    /
    kixfont    /
    kluwer    /
    knitting    /
    knittingpattern    /
    knuth    /
    knuth-lib    /
    knuth-local    /
    knuthotherfonts    /
    koma-moderncvclassic    /
    koma-script    /
    koma-script-examples    /
    koma-script-sfs    /
    komacv    /
    kotex-oblivoir    /
    kotex-plain    /
    kotex-utf    /
    kotex-utils    /
    kotex-utils.x86_64-linux    /
    kpathsea    /
    kpathsea.x86_64-linux    /
    kpfonts    /
    ksfh_nat    /
    ksp-thesis    /
    ktv-texdata    /
    kurier    /
    l2picfaq    /
    l2tabu    /
    l2tabu-english    /
    l2tabu-french    /
    l2tabu-italian    /
    l2tabu-spanish    /
    l3build    /
    l3experimental    /
    l3kernel    /
    l3packages    /
    labbook    /
    labels    /
    labyrinth    /
    lacheck    /
    lacheck.x86_64-linux    /
    lambda    /
    lambda-lists    /
    langcode    /
    langsci    /
    lapdf    /
    lastpackage    /
    lastpage    /
    latex    /
    latex-bib-ex    /
    latex-bib2-ex    /
    latex-bin    /
    latex-bin.x86_64-linux    /
    latex-brochure    /
    latex-course    /
    latex-doc-ptr    /
    latex-fonts    /
    latex-git-log    /
    latex-git-log.x86_64-linux    /
    latex-graphics-companion    /
    latex-make    /
    latex-notes-zh-cn    /
    latex-papersize    /
    latex-papersize.x86_64-linux    /
    latex-referenz    /
    latex-tabellen    /
    latex-tds    /
    latex-veryshortguide    /
    latex-web-companion    /
    latex2e-help-texinfo    /
    latex2e-help-texinfo-fr    /
    latex2e-help-texinfo-spanish    /
    latex2man    /
    latex2man.x86_64-linux    /
    latex2nemeth    /
    latex2nemeth.x86_64-linux    /
    latex4wp    /
    latex4wp-it    /
    latexbangla    /
    latexbug    /
    latexcheat    /
    latexcheat-de    /
    latexcheat-esmx    /
    latexcheat-ptbr    /
    latexconfig    /
    latexcourse-rug    /
    latexdemo    /
    latexdiff    /
    latexdiff.x86_64-linux    /
    latexfileinfo-pkgs    /
    latexfileversion    /
    latexfileversion.x86_64-linux    /
    latexgit    /
    latexindent    /
    latexindent.x86_64-linux    /
    latexmk    /
    latexmk.x86_64-linux    /
    latexmp    /
    latexpand    /
    latexpand.x86_64-linux    /
    lato    /
    layaureo    /
    layouts    /
    lazylist    /
    lcd    /
    lcdftypetools    /
    lcdftypetools.x86_64-linux    /
    lcg    /
    lcyw    /
    leading    /
    leadsheets    /
    leaflet    /
    lecturer    /
    ledmac    /
    leftidx    /
    leipzig    /
    lengthconvert    /
    lettre    /
    lettrine    /
    levy    /
    lewis    /
    lexikon    /
    lexref    /
    lfb    /
    lgreek    /
    lh    /
    lhcyr    /
    lhelp    /
    libertine    /
    libertinegc    /
    libertinus    /
    libertinust1math    /
    libgreek    /
    librarian    /
    librebaskerville    /
    librebodoni    /
    librecaslon    /
    libris    /
    lilyglyphs    /
    lilyglyphs.x86_64-linux    /
    limap    /
    linearA    /
    linegoal    /
    lineno    /
    ling-macros    /
    linguex    /
    linop    /
    lipsum    /
    lisp-on-tex    /
    listbib    /
    listbib.x86_64-linux    /
    listing    /
    listings    /
    listings-ext    /
    listings-ext.x86_64-linux    /
    listlbls    /
    listliketab    /
    listofitems    /
    listofsymbols    /
    lithuanian    /
    liturg    /
    lkproof    /
    lm    /
    lm-math    /
    lmake    /
    lobster2    /
    locality    /
    localloc    /
    logbox    /
    logical-markup-utils    /
    logicproof    /
    logicpuzzle    /
    logpap    /
    logreq    /
    lollipop    /
    lollipop.x86_64-linux    /
    longdivision    /
    longfbox    /
    longfigure    /
    longnamefilelist    /
    loops    /
    lpform    /
    lpic    /
    lplfitch    /
    lps    /
    lroundrect    /
    lsc    /
    lshort-bulgarian    /
    lshort-chinese    /
    lshort-czech    /
    lshort-dutch    /
    lshort-english    /
    lshort-estonian    /
    lshort-finnish    /
    lshort-french    /
    lshort-german    /
    lshort-italian    /
    lshort-japanese    /
    lshort-korean    /
    lshort-mongol    /
    lshort-persian    /
    lshort-polish    /
    lshort-portuguese    /
    lshort-russian    /
    lshort-slovak    /
    lshort-slovenian    /
    lshort-spanish    /
    lshort-thai    /
    lshort-turkish    /
    lshort-ukr    /
    lshort-vietnamese    /
    lstaddons    /
    lstbayes    /
    lt3graph    /
    ltablex    /
    ltabptch    /
    ltxdockit    /
    ltxfileinfo    /
    ltxfileinfo.x86_64-linux    /
    ltximg    /
    ltximg.x86_64-linux    /
    ltxindex    /
    ltxkeys    /
    ltxmisc    /
    ltxnew    /
    ltxtools    /
    lua-alt-getopt    /
    lua-check-hyphen    /
    lua-visual-debug    /
    lua2dox    /
    lua2dox.x86_64-linux    /
    luabibentry    /
    luabidi    /
    luacode    /
    luahyphenrules    /
    luaindex    /
    luainputenc    /
    luaintro    /
    lualatex-doc    /
    lualatex-doc-de    /
    lualatex-math    /
    lualibs    /
    luamplib    /
    luaotfload    /
    luaotfload.x86_64-linux    /
    luasseq    /
    luatex    /
    luatex.x86_64-linux    /
    luatex85    /
    luatexbase    /
    luatexja    /
    luatexko    /
    luatextra    /
    luatodonotes    /
    luaxml    /
    lxfonts    /
    ly1    /
    m-tx    /
    m-tx.x86_64-linux    /
    macros2e    /
    macroswap    /
    mafr    /
    magaz    /
    mailing    /
    mailmerge    /
    make4ht    /
    make4ht.x86_64-linux    /
    makebarcode    /
    makebase    /
    makebox    /
    makecell    /
    makecirc    /
    makecmds    /
    makedtx    /
    makedtx.x86_64-linux    /
    makeglos    /
    makeindex    /
    makeindex.x86_64-linux    /
    makeplot    /
    makeshape    /
    mandi    /
    manfnt    /
    manfnt-font    /
    manuscript    /
    margbib    /
    marginfix    /
    marginnote    /
    markdown    /
    marvosym    /
    matc3    /
    matc3mem    /
    match_parens    /
    match_parens.x86_64-linux    /
    math-e    /
    math-into-latex-4    /
    mathabx    /
    mathabx-type1    /
    mathalfa    /
    mathastext    /
    mathcomp    /
    mathdesign    /
    mathdots    /
    mathexam    /
    mathpartir    /
    mathpazo    /
    maths-symbols    /
    mathspec    /
    mathspic    /
    mathspic.x86_64-linux    /
    mathtools    /
    matlab-prettifier    /
    mattens    /
    maybemath    /
    mbenotes    /
    mcaption    /
    mceinleger    /
    mcf2graph    /
    mcite    /
    mciteplus    /
    mcmthesis    /
    mdframed    /
    mdputu    /
    mdsymbol    /
    mdwtools    /
    media9    /
    medstarbeamer    /
    meetingmins    /
    memdesign    /
    memexsupp    /
    memoir    /
    memory    /
    mendex-doc    /
    mentis    /
    menu    /
    menukeys    /
    merriweather    /
    metafont    /
    metafont-beginners    /
    metafont.x86_64-linux    /
    metago    /
    metalogo    /
    metaobj    /
    metaplot    /
    metapost    /
    metapost-examples    /
    metapost.x86_64-linux    /
    metatex    /
    metatype1    /
    metauml    /
    method    /
    metre    /
    metrix    /
    mex    /
    mex.x86_64-linux    /
    mf2pt1    /
    mf2pt1.x86_64-linux    /
    mfirstuc    /
    mflogo    /
    mflogo-font    /
    mflua    /
    mflua.x86_64-linux    /
    mfnfss    /
    mfpic    /
    mfpic4ode    /
    mftinc    /
    mfware    /
    mfware.x86_64-linux    /
    mgltex    /
    mhchem    /
    mhequ    /
    miama    /
    microtype    /
    microtype-de    /
    midnight    /
    midpage    /
    miller    /
    milog    /
    minibox    /
    minifp    /
    minipage-marginpar    /
    miniplot    /
    minitoc    /
    minorrevision    /
    minted    /
    mintspirit    /
    minutes    /
    missaali    /
    mkgrkindex    /
    mkgrkindex.x86_64-linux    /
    mkjobtexmf    /
    mkjobtexmf.x86_64-linux    /
    mkpattern    /
    mkpic    /
    mkpic.x86_64-linux    /
    mla-paper    /
    mlist    /
    mltex    /
    mltex.x86_64-linux    /
    mmap    /
    mnotes    /
    mnras    /
    mnsymbol    /
    moderncv    /
    moderntimeline    /
    modiagram    /
    modref    /
    modroman    /
    mongolian-babel    /
    monofill    /
    montex    /
    montserrat    /
    moodle    /
    moreenum    /
    morefloats    /
    morehype    /
    moresize    /
    moreverb    /
    morewrites    /
    movie15    /
    mp3d    /
    mparhack    /
    mparrows    /
    mpattern    /
    mpcolornames    /
    mpgraphics    /
    mpman-ru    /
    mpostinl    /
    mptopdf    /
    mptopdf.x86_64-linux    /
    ms    /
    msc    /
    msg    /
    mslapa    /
    msu-thesis    /
    mtgreek    /
    mugsthesis    /
    multenum    /
    multiaudience    /
    multibbl    /
    multibib    /
    multibibliography    /
    multibibliography.x86_64-linux    /
    multicap    /
    multidef    /
    multido    /
    multienv    /
    multiexpand    /
    multiobjective    /
    multirow    /
    munich    /
    musixguit    /
    musixtex    /
    musixtex-fonts    /
    musixtex.x86_64-linux    /
    musixtnt    /
    musixtnt.x86_64-linux    /
    musuos    /
    muthesis    /
    mversion    /
    mwcls    /
    mwe    /
    mweights    /
    mxedruli    /
    mychemistry    /
    mycv    /
    mylatexformat    /
    mynsfc    /
    nag    /
    nameauth    /
    namespc    /
    nanumtype1    /
    nar    /
    natbib    /
    natded    /
    nath    /
    nature    /
    navigator    /
    navydocs    /
    ncclatex    /
    ncctools    /
    ncntrsbk    /
    nddiss    /
    ndsu-thesis    /
    needspace    /
    nestquot    /
    neuralnetwork    /
    nevelok    /
    newcommand    /
    newenviron    /
    newfile    /
    newlfm    /
    newpx    /
    newsletr    /
    newspaper    /
    newtx    /
    newtxsf    /
    newtxtt    /
    newunicodechar    /
    newvbtm    /
    newverbs    /
    nextpage    /
    nfssext-cfr    /
    nicefilelist    /
    niceframe    /
    nicetext    /
    nih    /
    nihbiosketch    /
    nimbus15    /
    nkarta    /
    nlctdoc    /
    nmbib    /
    noconflict    /
    nodetree    /
    noindentafter    /
    noitcrul    /
    nolbreaks    /
    nomencl    /
    nomentbl    /
    nonfloat    /
    nonumonpart    /
    nopageno    /
    norasi-c90    /
    normalcolor    /
    nostarch    /
    notes    /
    notes2bib    /
    notespages    /
    notex-bst    /
    noto    /
    notoccite    /
    nowidow    /
    nox    /
    nrc    /
    ntgclass    /
    ntheorem    /
    ntheorem-vn    /
    nuc    /
    nucleardata    /
    numberedblock    /
    numericplots    /
    numname    /
    numprint    /
    nwejm    /
    oberdiek    /
    objectz    /
    obnov    /
    ocg-p    /
    ocgx    /
    ocgx2    /
    ocherokee    /
    ocr-b    /
    ocr-b-outline    /
    ocr-latex    /
    octavo    /
    odsfile    /
    ofs    /
    ogham    /
    oinuit    /
    old-arrows    /
    oldlatin    /
    oldstandard    /
    oldstyle    /
    olsak-misc    /
    omega    /
    omegaware    /
    omegaware.x86_64-linux    /
    onlyamsmath    /
    onrannual    /
    opcit    /
    opensans    /
    oplotsymbl    /
    opteng    /
    optidef    /
    optional    /
    options    /
    ordinalpt    /
    orkhun    /
    oscola    /
    ot-tableau    /
    othello    /
    othelloboard    /
    otibet    /
    oubraces    /
    outline    /
    outliner    /
    outlines    /
    overlays    /
    overlock    /
    overpic    /
    pacioli    /
    padauk    /
    pagecolor    /
    pagecont    /
    pagenote    /
    pagerange    /
    pageslts    /
    palatino    /
    paper    /
    papercdcase    /
    papermas    /
    papertex    /
    paracol    /
    parades    /
    paralist    /
    parallel    /
    paratype    /
    paresse    /
    parnotes    /
    parrun    /
    parselines    /
    parskip    /
    pas-cours    /
    pas-crosswords    /
    pas-cv    /
    pas-tableur    /
    passivetex    /
    patch    /
    patchcmd    /
    patgen    /
    patgen.x86_64-linux    /
    patgen2-tutorial    /
    path    /
    pauldoc    /
    pawpict    /
    pax    /
    pax.x86_64-linux    /
    pb-diagram    /
    pbibtex-base    /
    pbox    /
    pbsheet    /
    pdf-trans    /
    pdf14    /
    pdfbook2    /
    pdfbook2.x86_64-linux    /
    pdfcomment    /
    pdfcprot    /
    pdfcrop    /
    pdfcrop.x86_64-linux    /
    pdfjam    /
    pdfjam.x86_64-linux    /
    pdflatexpicscale    /
    pdflatexpicscale.x86_64-linux    /
    pdfmarginpar    /
    pdfpagediff    /
    pdfpages    /
    pdfscreen    /
    pdfslide    /
    pdfsync    /
    pdftex    /
    pdftex.x86_64-linux    /
    pdftools    /
    pdftools.x86_64-linux    /
    pdftricks    /
    pdftricks2    /
    pdfwin    /
    pdfx    /
    pdfxup    /
    pdfxup.x86_64-linux    /
    pecha    /
    pedigree-perl    /
    pedigree-perl.x86_64-linux    /
    perception    /
    perfectcut    /
    perltex    /
    perltex.x86_64-linux    /
    permute    /
    persian-bib    /
    petiteannonce    /
    petri-nets    /
    petri-nets.x86_64-linux    /
    pfarrei    /
    pfarrei.x86_64-linux    /
    pgf    /
    pgf-blur    /
    pgf-soroban    /
    pgf-spectra    /
    pgf-umlcd    /
    pgf-umlsd    /
    pgfgantt    /
    pgfkeyx    /
    pgfmolbio    /
    pgfopts    /
    pgfornament    /
    pgfplots    /
    phaistos    /
    phffullpagefigure    /
    phfnote    /
    phfparen    /
    phfqit    /
    phfquotetext    /
    phfsvnwatermark    /
    phfthm    /
    philex    /
    philokalia    /
    philosophersimprint    /
    phonenumbers    /
    phonetic    /
    phonrule    /
    photo    /
    physics    /
    piano    /
    picinpar    /
    pict2e    /
    pictex    /
    pictex2    /
    pictexsum    /
    piechartmp    /
    piff    /
    pigpen    /
    pinlabel    /
    pitex    /
    pittetd    /
    pkfix    /
    pkfix-helper    /
    pkfix-helper.x86_64-linux    /
    pkfix.x86_64-linux    /
    pkgloader    /
    pkuthss    /
    pl    /
    placeat    /
    placeins    /
    placeins-plain    /
    plain    /
    plain-doc    /
    plainpkg    /
    plantslabels    /
    plari    /
    plates    /
    platex    /
    platex-tools    /
    platex.x86_64-linux    /
    platexcheat    /
    play    /
    playfair    /
    plipsum    /
    plnfss    /
    plstmary    /
    plweb    /
    pmgraph    /
    pmx    /
    pmx.x86_64-linux    /
    pmxchords    /
    pmxchords.x86_64-linux    /
    pnas2009    /
    poemscol    /
    poetrytex    /
    polski    /
    poltawski    /
    polyglossia    /
    polynom    /
    polynomial    /
    polytable    /
    postcards    /
    poster-mac    /
    powerdot    /
    powerdot-FUBerlin    /
    ppr-prv    /
    pracjourn    /
    preprint    /
    prerex    /
    present    /
    presentations    /
    presentations-en    /
    pressrelease    /
    prettyref    /
    preview    /
    prftree    /
    printlen    /
    proba    /
    probsoln    /
    procIAGssymp    /
    prodint    /
    productbox    /
    program    /
    progress    /
    progressbar    /
    proofread    /
    prooftrees    /
    properties    /
    proposal    /
    prosper    /
    protex    /
    protocol    /
    przechlewski-book    /
    ps2pk    /
    ps2pk.x86_64-linux    /
    psbao    /
    pseudocode    /
    psfrag    /
    psfrag-italian    /
    psfragx    /
    psgo    /
    psizzl    /
    pslatex    /
    psnfss    /
    pspicture    /
    pst-2dplot    /
    pst-3d    /
    pst-3dplot    /
    pst-abspos    /
    pst-am    /
    pst-arrow    /
    pst-asr    /
    pst-bar    /
    pst-barcode    /
    pst-bezier    /
    pst-blur    /
    pst-bspline    /
    pst-calendar    /
    pst-cie    /
    pst-circ    /
    pst-coil    /
    pst-cox    /
    pst-dbicons    /
    pst-diffraction    /
    pst-electricfield    /
    pst-eps    /
    pst-eucl    /
    pst-eucl-translation-bg    /
    pst-exa    /
    pst-fill    /
    pst-fit    /
    pst-fr3d    /
    pst-fractal    /
    pst-fun    /
    pst-func    /
    pst-gantt    /
    pst-geo    /
    pst-ghsb    /
    pst-gr3d    /
    pst-grad    /
    pst-graphicx    /
    pst-infixplot    /
    pst-intersect    /
    pst-jtree    /
    pst-knot    /
    pst-labo    /
    pst-layout    /
    pst-lens    /
    pst-light3d    /
    pst-magneticfield    /
    pst-math    /
    pst-mirror    /
    pst-node    /
    pst-ob3d    /
    pst-ode    /
    pst-optexp    /
    pst-optic    /
    pst-osci    /
    pst-ovl    /
    pst-pad    /
    pst-pdf    /
    pst-pdf.x86_64-linux    /
    pst-pdgr    /
    pst-perspective    /
    pst-platon    /
    pst-plot    /
    pst-poly    /
    pst-pulley    /
    pst-qtree    /
    pst-rubans    /
    pst-shell    /
    pst-sigsys    /
    pst-slpe    /
    pst-solarsystem    /
    pst-solides3d    /
    pst-soroban    /
    pst-spectra    /
    pst-spirograph    /
    pst-stru    /
    pst-support    /
    pst-text    /
    pst-thick    /
    pst-tools    /
    pst-tree    /
    pst-tvz    /
    pst-uml    /
    pst-vectorian    /
    pst-vowel    /
    pst-vue3d    /
    pst2pdf    /
    pst2pdf.x86_64-linux    /
    pstool    /
    pstools    /
    pstools.x86_64-linux    /
    pstricks    /
    pstricks-add    /
    pstricks_calcnotes    /
    pstring    /
    psu-thesis    /
    psutils    /
    psutils.x86_64-linux    /
    ptex    /
    ptex-base    /
    ptex-fontmaps    /
    ptex-fontmaps.x86_64-linux    /
    ptex-fonts    /
    ptex.x86_64-linux    /
    ptex2pdf    /
    ptex2pdf.x86_64-linux    /
    ptext    /
    ptptex    /
    punk    /
    punk-latex    /
    punknova    /
    purifyeps    /
    purifyeps.x86_64-linux    /
    pxbase    /
    pxchfon    /
    pxcjkcat    /
    pxfonts    /
    pxgreeks    /
    pxjahyper    /
    pxpgfmark    /
    pxrubrica    /
    pxtatescale    /
    pxtxalfa    /
    pygmentex    /
    pygmentex.x86_64-linux    /
    python    /
    pythontex    /
    pythontex.x86_64-linux    /
    qcircuit    /
    qcm    /
    qobitree    /
    qpxqtx    /
    qrcode    /
    qstest    /
    qsymbols    /
    qtree    /
    quattrocento    /
    quicktype    /
    quotchap    /
    quoting    /
    quotmark    /
    quran    /
    r_und_s    /
    raleway    /
    ran_toks    /
    randbild    /
    randomlist    /
    randomwalk    /
    randtext    /
    rccol    /
    rcs    /
    rcs-multi    /
    rcsinfo    /
    readarray    /
    realboxes    /
    realscripts    /
    rec-thy    /
    recipe    /
    recipebook    /
    recipecard    /
    rectopma    /
    recycle    /
    refcheck    /
    refenums    /
    reflectgraphics    /
    refman    /
    refstyle    /
    regcount    /
    regexpatch    /
    register    /
    regstats    /
    reledmac    /
    relenc    /
    relsize    /
    reotex    /
    repeatindex    /
    repere    /
    repltext    /
    resphilosophica    /
    resumecls    /
    resumemac    /
    reverxii    /
    revquantum    /
    revtex    /
    revtex4    /
    ribbonproofs    /
    rjlparshap    /
    rlepsf    /
    rmathbr    /
    rmpage    /
    roboto    /
    robustcommand    /
    robustindex    /
    roex    /
    romanbar    /
    romanbarpagenumber    /
    romande    /
    romanneg    /
    romannum    /
    rosario    /
    rotfloat    /
    rotpages    /
    roundbox    /
    roundrect    /
    rrgtrees    /
    rsc    /
    rsfs    /
    rsfso    /
    rterface    /
    rtkinenc    /
    rtklage    /
    rubik    /
    rubik.x86_64-linux    /
    ruhyphen    /
    rulercompass    /
    russ    /
    rviewport    /
    rvwrite    /
    ryethesis    /
    sa-tikz    /
    sageep    /
    sanitize-umlaut    /
    sanskrit    /
    sanskrit-t1    /
    sansmath    /
    sansmathaccent    /
    sansmathfonts    /
    sapthesis    /
    sasnrdisplay    /
    sauerj    /
    sauter    /
    sauterfonts    /
    savefnmark    /
    savesym    /
    savetrees    /
    scale    /
    scalebar    /
    scalerel    /
    scanpages    /
    schemabloc    /
    schemata    /
    scheme-basic    /
    scheme-context    /
    scheme-full    /
    scheme-gust    /
    scheme-infraonly    /
    scheme-medium    /
    scheme-minimal    /
    scheme-small    /
    scheme-tetex    /
    scheme-xml    /
    schule    /
    schulschriften    /
    schwalbe-chess    /
    sciposter    /
    sclang-prettifier    /
    screenplay    /
    screenplay-pkg    /
    scrjrnl    /
    scrlttr2copy    /
    scsnowman    /
    sdrt    /
    sduthesis    /
    secdot    /
    section    /
    sectionbox    /
    sectsty    /
    seealso    /
    seetexk    /
    seetexk.x86_64-linux    /
    selectp    /
    selnolig    /
    semantic    /
    semantic-markup    /
    semaphor    /
    seminar    /
    semioneside    /
    semproc    /
    sepfootnotes    /
    sepnum    /
    seqsplit    /
    serbian-apostrophe    /
    serbian-date-lat    /
    serbian-def-cyr    /
    serbian-lig    /
    sesamanuel    /
    setdeck    /
    setspace    /
    seuthesis    /
    seuthesix    /
    sf298    /
    sffms    /
    sfg    /
    sfmath    /
    sgame    /
    shade    /
    shadethm    /
    shadow    /
    shadowtext    /
    shapepar    /
    shapes    /
    shdoc    /
    shipunov    /
    shorttoc    /
    show2e    /
    showcharinbox    /
    showdim    /
    showexpl    /
    showhyphens    /
    showlabels    /
    showtags    /
    shuffle    /
    sidecap    /
    sidenotes    /
    sides    /
    signchart    /
    silence    /
    simple-resume-cv    /
    simple-thesis-dissertation    /
    simplecd    /
    simplecv    /
    simpler-wick    /
    simplewick    /
    simplified-latex    /
    simurgh    /
    sitem    /
    siunitx    /
    skak    /
    skaknew    /
    skb    /
    skdoc    /
    skeycommand    /
    skeyval    /
    skmath    /
    skrapport    /
    skull    /
    slantsc    /
    slideshow    /
    smalltableof    /
    smartdiagram    /
    smartref    /
    smartunits    /
    snapshot    /
    snotez    /
    songbook    /
    songs    /
    sort-by-letters    /
    soton    /
    soul    /
    soup    /
    sourcecodepro    /
    sourcesanspro    /
    sourceserifpro    /
    spalign    /
    spanish-mx    /
    sparklines    /
    spath3    /
    spelling    /
    sphack    /
    sphdthesis    /
    spie    /
    splines    /
    splitbib    /
    splitindex    /
    splitindex.x86_64-linux    /
    spot    /
    spotcolor    /
    spreadtab    /
    spverbatim    /
    sr-vorl    /
    srbook-mem    /
    srcltx    /
    srcredact    /
    srcredact.x86_64-linux    /
    sseq    /
    sslides    /
    stack    /
    stackengine    /
    stage    /
    standalone    /
    stanli    /
    starfont    /
    startex    /
    statex    /
    statex2    /
    statistik    /
    staves    /
    stdclsdv    /
    stdpage    /
    steinmetz    /
    stellenbosch    /
    stex    /
    stix    /
    stmaryrd    /
    storebox    /
    storecmd    /
    stringstrings    /
    struktex    /
    sttools    /
    stubs    /
    sty2dtx    /
    sty2dtx.x86_64-linux    /
    suanpan    /
    subdepth    /
    subeqn    /
    subeqnarray    /
    subfig    /
    subfigmat    /
    subfigure    /
    subfiles    /
    subfloat    /
    substances    /
    substitutefont    /
    substr    /
    subsupscripts    /
    sudoku    /
    sudokubundle    /
    suftesi    /
    sugconf    /
    superiors    /
    supertabular    /
    susy    /
    svg    /
    svg-inkscape    /
    svgcolor    /
    svn    /
    svn-multi    /
    svn-multi.x86_64-linux    /
    svn-prov    /
    svninfo    /
    svrsymbols    /
    swebib    /
    swimgraf    /
    syllogism    /
    symbol    /
    sympytexpackage    /
    synctex    /
    synctex.x86_64-linux    /
    synproof    /
    syntax    /
    syntrace    /
    synttree    /
    systeme    /
    t-angles    /
    t1utils    /
    t1utils.x86_64-linux    /
    t2    /
    tabfigures    /
    table-fct    /
    tableaux    /
    tablefootnote    /
    tableof    /
    tablestyles    /
    tablists    /
    tablor    /
    tabls    /
    tabriz-thesis    /
    tabstackengine    /
    tabto-generic    /
    tabto-ltx    /
    tabu    /
    tabularborder    /
    tabularcalc    /
    tabularew    /
    tabulars-e    /
    tabulary    /
    tabvar    /
    tagging    /
    tagpair    /
    talk    /
    tamefloats    /
    tamethebeast    /
    tap    /
    tapir    /
    tasks    /
    tcldoc    /
    tcolorbox    /
    tdclock    /
    tds    /
    tdsfrmath    /
    technics    /
    ted    /
    templates-fenn    /
    templates-sommer    /
    templatetools    /
    tempora    /
    tengwarscript    /
    tensor    /
    termcal    /
    termlist    /
    termmenu    /
    testhyphens    /
    testidx    /
    tetex    /
    tetex.x86_64-linux    /
    teubner    /
    tex    /
    tex-ewd    /
    tex-font-errors-cheatsheet    /
    tex-gyre    /
    tex-gyre-math    /
    tex-ini-files    /
    tex-label    /
    tex-overview    /
    tex-ps    /
    tex-refs    /
    tex-virtual-academy-pl    /
    tex.x86_64-linux    /
    tex4ebook    /
    tex4ebook.x86_64-linux    /
    tex4ht    /
    tex4ht.x86_64-linux    /
    texapi    /
    texbytopic    /
    texconfig    /
    texconfig.x86_64-linux    /
    texcount    /
    texcount.x86_64-linux    /
    texdef    /
    texdef.x86_64-linux    /
    texdiff    /
    texdiff.x86_64-linux    /
    texdirflatten    /
    texdirflatten.x86_64-linux    /
    texdoc    /
    texdoc.x86_64-linux    /
    texdraw    /
    texfot    /
    texfot.x86_64-linux    /
    texilikechaps    /
    texilikecover    /
    texinfo    /
    texlive-common    /
    texlive-cz    /
    texlive-de    /
    texlive-docindex    /
    texlive-en    /
    texlive-es    /
    texlive-fr    /
    texlive-it    /
    texlive-msg-translations    /
    texlive-pl    /
    texlive-ru    /
    texlive-scripts    /
    texlive-scripts.x86_64-linux    /
    texlive-sr    /
    texlive-zh-cn    /
    texlive.infra    /
    texlive.infra.x86_64-linux    /
    texliveonfly    /
    texliveonfly.x86_64-linux    /
    texloganalyser    /
    texloganalyser.x86_64-linux    /
    texlogos    /
    texmate    /
    texments    /
    texosquery    /
    texosquery.x86_64-linux    /
    texpower    /
    texproposal    /
    texshade    /
    texsis    /
    texsis.x86_64-linux    /
    textcase    /
    textfit    /
    textglos    /
    textgreek    /
    textmerg    /
    textopo    /
    textpath    /
    textpos    /
    texvc    /
    texware    /
    texware.x86_64-linux    /
    texworks    /
    tfrupee    /
    thalie    /
    theoremref    /
    thesis-ekf    /
    thesis-titlepage-fhac    /
    thinsp    /
    thmbox    /
    thmtools    /
    threadcol    /
    threeddice    /
    threeparttable    /
    threeparttablex    /
    thumb    /
    thumbpdf    /
    thumbpdf.x86_64-linux    /
    thumbs    /
    thumby    /
    thuthesis    /
    ticket    /
    ticollege    /
    tie    /
    tie.x86_64-linux    /
    tikz-3dplot    /
    tikz-bayesnet    /
    tikz-cd    /
    tikz-dependency    /
    tikz-dimline    /
    tikz-feynman    /
    tikz-inet    /
    tikz-kalender    /
    tikz-opm    /
    tikz-optics    /
    tikz-page    /
    tikz-palattice    /
    tikz-qtree    /
    tikz-timing    /
    tikzinclude    /
    tikzmark    /
    tikzorbital    /
    tikzpagenodes    /
    tikzpeople    /
    tikzpfeile    /
    tikzposter    /
    tikzscale    /
    tikzsymbols    /
    times    /
    timetable    /
    timing-diagrams    /
    tinos    /
    tipa    /
    tipa-de    /
    tipfr    /
    titlecaps    /
    titlefoot    /
    titlepages    /
    titlepic    /
    titleref    /
    titlesec    /
    titling    /
    tkz-base    /
    tkz-berge    /
    tkz-doc    /
    tkz-euclide    /
    tkz-fct    /
    tkz-graph    /
    tkz-kiviat    /
    tkz-linknodes    /
    tkz-orm    /
    tkz-tab    /
    tlc2    /
    tocbibind    /
    tocdata    /
    tocloft    /
    tocvsec2    /
    todo    /
    todonotes    /
    tokenizer    /
    toolbox    /
    tools    /
    topfloat    /
    toptesi    /
    totcount    /
    totpages    /
    tpic2pdftex    /
    tpic2pdftex.x86_64-linux    /
    tpslifonts    /
    tqft    /
    tracklang    /
    trajan    /
    tram    /
    translation-array-fr    /
    translation-arsclassica-de    /
    translation-biblatex-de    /
    translation-chemsym-de    /
    translation-dcolumn-fr    /
    translation-ecv-de    /
    translation-enumitem-de    /
    translation-europecv-de    /
    translation-filecontents-de    /
    translation-moreverb-de    /
    translation-natbib-fr    /
    translation-tabbing-fr    /
    translations    /
    tree-dvips    /
    treetex    /
    trfsigns    /
    trigonometry    /
    trimspaces    /
    trivfloat    /
    trsym    /
    truncate    /
    tsemlines    /
    ttfutils    /
    ttfutils.x86_64-linux    /
    tucv    /
    tudscr    /
    tufte-latex    /
    tugboat    /
    tugboat-plain    /
    tui    /
    turabian    /
    turabian-formatting    /
    turkmen    /
    turnstile    /
    turnthepage    /
    twoinone    /
    twoup    /
    txfonts    /
    txfontsb    /
    txgreeks    /
    type1cm    /
    typed-checklist    /
    typeface    /
    typehtml    /
    typeoutfileinfo    /
    typeoutfileinfo.x86_64-linux    /
    typicons    /
    typogrid    /
    uaclasses    /
    uafthesis    /
    uantwerpendocs    /
    uassign    /
    ucbthesis    /
    ucdavisthesis    /
    ucharcat    /
    ucharclasses    /
    ucs    /
    ucthesis    /
    udesoftec    /
    uebungsblatt    /
    uestcthesis    /
    uhc    /
    uhrzeit    /
    uiucredborder    /
    uiucthesis    /
    ukrhyph    /
    ulem    /
    ulqda    /
    ulqda.x86_64-linux    /
    ulthese    /
    umbclegislation    /
    umich-thesis    /
    uml    /
    umlaute    /
    umoline    /
    umthesis    /
    umtypewriter    /
    unamth-template    /
    unamthesis    /
    undergradmath    /
    underlin    /
    underoverlap    /
    underscore    /
    undolabl    /
    unfonts-core    /
    unfonts-extra    /
    uni-wtal-ger    /
    uni-wtal-lin    /
    unicode-bidi    /
    unicode-data    /
    unicode-math    /
    unisugar    /
    units    /
    unitsdef    /
    universa    /
    universalis    /
    unravel    /
    unswcover    /
    uothesis    /
    uowthesis    /
    uowthesistitlepage    /
    upca    /
    updmap-map    /
    uplatex    /
    uplatex.x86_64-linux    /
    upmethodology    /
    uppunctlm    /
    upquote    /
    uptex    /
    uptex-base    /
    uptex-fonts    /
    uptex.x86_64-linux    /
    urcls    /
    uri    /
    url    /
    urlbst    /
    urlbst.x86_64-linux    /
    urwchancal    /
    usebib    /
    ushort    /
    uspace    /
    uspatent    /
    ut-thesis    /
    utf8mex    /
    utopia    /
    uwmslide    /
    uwthesis    /
    vak    /
    vancouver    /
    variations    /
    varindex    /
    varisize    /
    varsfromjobname    /
    varwidth    /
    vaucanson-g    /
    vdmlisting    /
    velthuis    /
    velthuis.x86_64-linux    /
    venn    /
    venndiagram    /
    venturisadf    /
    verbasef    /
    verbatimbox    /
    verbatimcopy    /
    verbdef    /
    verbments    /
    verse    /
    version    /
    versions    /
    versonotes    /
    vertbars    /
    vgrid    /
    vhistory    /
    visualfaq    /
    visualpstricks    /
    visualtikz    /
    vlna    /
    vlna.x86_64-linux    /
    vmargin    /
    vntex    /
    vocaltract    /
    volumes    /
    voss-mathcol    /
    vpe    /
    vpe.x86_64-linux    /
    vruler    /
    vwcol    /
    wadalab    /
    wallpaper    /
    warning    /
    warpcol    /
    was    /
    wasy    /
    wasy2-ps    /
    wasysym    /
    web    /
    web.x86_64-linux    /
    webguide    /
    widetable    /
    williams    /
    withargs    /
    wnri    /
    wnri-latex    /
    wordcount    /
    wordlike    /
    wrapfig    /
    wsemclassic    /
    wsuipa    /
    wtref    /
    xargs    /
    xassoccnt    /
    xcharter    /
    xcite    /
    xcjk2uni    /
    xcntperchap    /
    xcolor    /
    xcolor-material    /
    xcolor-solarized    /
    xcomment    /
    xcookybooky    /
    xdoc    /
    xduthesis    /
    xdvi    /
    xdvi.x86_64-linux    /
    xebaposter    /
    xecjk    /
    xecolor    /
    xecyr    /
    xeindex    /
    xellipsis    /
    xepersian    /
    xesearch    /
    xespotcolor    /
    xetex    /
    xetex-devanagari    /
    xetex-itrans    /
    xetex-pstricks    /
    xetex-tibetan    /
    xetex.x86_64-linux    /
    xetexconfig    /
    xetexfontinfo    /
    xetexko    /
    xetexref    /
    xevlna    /
    xfor    /
    xgreek    /
    xhfill    /
    xifthen    /
    xii    /
    xindy    /
    xindy.x86_64-linux    /
    xint    /
    xits    /
    xkeyval    /
    xlop    /
    xltxtra    /
    xmltex    /
    xmltex.x86_64-linux    /
    xmltexconfig    /
    xmpincl    /
    xnewcommand    /
    xoptarg    /
    xpatch    /
    xpeek    /
    xpiano    /
    xpicture    /
    xpinyin    /
    xprintlen    /
    xpunctuate    /
    xq    /
    xsavebox    /
    xskak    /
    xstring    /
    xtab    /
    xunicode    /
    xwatermark    /
    xyling    /
    xymtex    /
    xypic    /
    xypic-tut-pt    /
    xytree    /
    yafoot    /
    yagusylo    /
    yaletter    /
    yannisgr    /
    yathesis    /
    yax    /
    ycbook    /
    ydoc    /
    yfonts    /
    yfonts-t1    /
    yhmath    /
    yinit-otf    /
    york-thesis    /
    youngtab    /
    yplan    /
    yplan.x86_64-linux    /
    ytableau    /
    zapfchan    /
    zapfding    /
    zed-csp    /
    zhmetrics    /
    zhmetrics-uptex    /
    zhnumber    /
    zhspacing    /
    ziffer    /
    zlmtt    /
    zwgetfdate    /
    zwpagelayout    /
    zxjafbfont    /
    zxjafont    /
    zxjatype

fi
