#!/bin/sh

APP_PATH=`echo $0 | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+1] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'`
APP_PATH=`cd "$APP_PATH"; pwd`

# See if there is a cached version of TL available
export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
if ! command -v lualatex > /dev/null; then
  # Obtain TeX Live
  wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  tar -xzf install-tl-unx.tar.gz
  cd install-tl-20*

  # Install a minimal system
  ./install-tl --profile="${APP_PATH}/texlive.profile"

  cd ..
fi

# Other contrib packages: done as a block to avoid multiple calls to tlmgr
tlmgr install   \
  adigraph \
  ae \
  amscls \
  amsfonts \
  amsmath \
  anysize \
  aobs-tikz \
  arabxetex \
  askmaps \
  asyfig \
  asypictureb \
  auto-pst-pdf-lua \
  autoarea \
  automata \
  awesomebox \
  babel \
  babel-english \
  babelbib \
  bardiag \
  bbcard \
  beamer \
  beamerswitch \
  bezierplot \
  bibtex \
  bibtex.x86_64-linux \
  bidi-atbegshi \
  bidicontour \
  bidipagegrid \
  bidipresentation \
  bidishadowtext \
  binarytree \
  blochsphere \
  blockdraw_mp \
  bloques \
  blox \
  bodegraph \
  bondgraph \
  bondgraphs \
  booktabs \
  bpolynomial \
  braids \
  breqn \
  bxeepic \
  cachepic \
  cachepic.x86_64-linux \
  callouts \
  caption \
  carlisle \
  celtic \
  changepage \
  checkcites \
  checkcites.x86_64-linux \
  chemfig \
  chickenize \
  circuitikz \
  cite \
  cm \
  cmap \
  cmarrows \
  collection-basic \
  collection-latex \
  collection-latexrecommended \
  collection-luatex \
  collection-metapost \
  collection-pictures \
  collection-xetex \
  colortbl \
  combinedgraphics \
  combofont \
  cqubeamer \
  crop \
  cstypo \
  ctable \
  ctablestack \
  curve \
  curve2e \
  curves \
  dcpic \
  diagmac2 \
  doc-pictex \
  dot2texi \
  dottex \
  dratex \
  drs \
  drv \
  duotenzor \
  dviincl \
  dvipdfmx \
  dvipdfmx.x86_64-linux \
  dvips \
  dvips.x86_64-linux \
  dynkin-diagrams \
  ecgdraw \
  eepic \
  ellipse \
  elocalloc \
  emp \
  enctex \
  endofproofwd \
  enigma \
  epsincl \
  epspdf \
  epspdf.x86_64-linux \
  epspdfconversion \
  esk \
  eso-pic \
  etex \
  etex-pkg \
  etoolbox \
  euenc \
  euler \
  expressg \
  exteps \
  extsizes \
  fancybox \
  fancyhdr \
  fancyref \
  fancyvrb \
  fast-diagram \
  featpost \
  feynmf \
  feynmp-auto \
  fig4latex \
  fig4latex.x86_64-linux \
  filehook \
  fitbox \
  fix2col \
  fixlatvian \
  float \
  flowchart \
  font-change-xetex \
  fontawesome \
  fontbook \
  fontloader-luaotfload \
  fontspec \
  fontwrap \
  forest \
  fp \
  framed \
  fvextra \
  garrigues \
  genealogytree \
  geometry \
  getmap \
  getmap.x86_64-linux \
  gincltex \
  glyphlist \
  gmp \
  gnuplottex \
  gradientframe \
  grafcet \
  graph35 \
  graphics \
  graphics-cfg \
  graphics-def \
  graphicxpsd \
  graphviz \
  gsftopk \
  gsftopk.x86_64-linux \
  gtrlib-largetrees \
  harveyballs \
  hatching \
  here \
  hf-tikz \
  hobby \
  hvfloat \
  hyperref \
  hyph-utf8 \
  hyphen-base \
  ifluatex \
  ifmtarg \
  ifplatform \
  iftex \
  ifxetex \
  index \
  interchar \
  interpreter \
  istgame \
  jknapltx \
  knitting \
  knittingpattern \
  knuth-lib \
  knuth-local \
  koma-script \
  kpathsea \
  kpathsea.x86_64-linux \
  l3experimental \
  l3kernel \
  l3packages \
  ladder \
  lapdf \
  lastpage \
  latex \
  latex-bin \
  latex-bin.x86_64-linux \
  latex-fonts \
  latex-make \
  latexbug \
  latexconfig \
  latexmp \
  lineno \
  listings \
  lm \
  lpic \
  lroundrect \
  ltxmisc \
  lua-alt-getopt \
  lua-visual-debug \
  lua2dox \
  lua2dox.x86_64-linux \
  luacode \
  luahyphenrules \
  luaindex \
  luainputenc \
  luaintro \
  lualatex-doc \
  lualatex-math \
  lualibs \
  luamesh \
  luamplib \
  luaotfload \
  luaotfload.x86_64-linux \
  luapackageloader \
  luasseq \
  luatex \
  luatex.x86_64-linux \
  luatex85 \
  luatexbase \
  luatexko \
  luatextra \
  luaxml \
  lwarp \
  lwarp.x86_64-linux \
  makecmds \
  makeindex \
  makeindex.x86_64-linux \
  maker \
  makeshape \
  mathspec \
  mathspic \
  mathspic.x86_64-linux \
  mathtools \
  mcf2graph \
  mdwtools \
  memoir \
  metafont \
  metafont.x86_64-linux \
  metago \
  metalogo \
  metaobj \
  metaplot \
  metapost \
  metapost.x86_64-linux \
  metauml \
  mflogo \
  mfnfss \
  mfpic \
  mfpic4ode \
  mfware \
  mfware.x86_64-linux \
  microtype \
  milsymb \
  miniplot \
  minted \
  mkpic \
  mkpic.x86_64-linux \
  modiagram \
  mp3d \
  mparrows \
  mpattern \
  mpcolornames \
  mpgraphics \
  mptopdf \
  mptopdf.x86_64-linux \
  mptrees \
  ms \
  na-position \
  natbib \
  neuralnetwork \
  nodetree \
  ntgclass \
  numericplots \
  oberdiek \
  odsfile \
  paralist \
  parskip \
  pb-diagram \
  pdfpages \
  pdftex \
  pdftex.x86_64-linux \
  petri-nets \
  petri-nets.x86_64-linux \
  pgf \
  pgf-blur \
  pgf-soroban \
  pgf-spectra \
  pgf-umlcd \
  pgf-umlsd \
  pgfgantt \
  pgfkeyx \
  pgfmolbio \
  pgfopts \
  pgfornament \
  pgfplots \
  philokalia \
  picinpar \
  pict2e \
  pictex \
  pictex2 \
  piechartmp \
  pinlabel \
  pixelart \
  placeat \
  placeins \
  plain \
  plantuml \
  pmgraph \
  polyglossia \
  powerdot \
  prerex \
  productbox \
  psfrag \
  pslatex \
  psnfss \
  pspicture \
  ptext \
  pxpgfmark \
  qcircuit \
  qrcode \
  quran \
  randbild \
  randomwalk \
  rcs \
  realscripts \
  reotex \
  repere \
  roex \
  roundrect \
  rviewport \
  sa-tikz \
  sansmath \
  sauerj \
  schemabloc \
  scheme-basic \
  scheme-infraonly \
  scheme-minimal \
  scratch \
  scsnowman \
  section \
  selnolig \
  seminar \
  sepnum \
  setdeck \
  setspace \
  shapes \
  signchart \
  simple-resume-cv \
  simple-thesis-dissertation \
  slideshow \
  smartdiagram \
  spath3 \
  spectralsequences \
  spelling \
  splines \
  suanpan \
  subfig \
  svn-prov \
  swimgraf \
  table-fct \
  tetex \
  tetex.x86_64-linux \
  tex \
  tex-ini-files \
  tex.x86_64-linux \
  texdraw \
  texlive-common \
  texlive-docindex \
  texlive-en \
  texlive-msg-translations \
  texlive-scripts \
  texlive-scripts.x86_64-linux \
  texlive.infra \
  texlive.infra.x86_64-linux \
  textcase \
  textpath \
  threeddice \
  thumbpdf \
  thumbpdf.x86_64-linux \
  ticollege \
  tikz-3dplot \
  tikz-bayesnet \
  tikz-cd \
  tikz-dependency \
  tikz-dimline \
  tikz-feynhand \
  tikz-feynman \
  tikz-inet \
  tikz-kalender \
  tikz-karnaugh \
  tikz-ladder \
  tikz-layers \
  tikz-opm \
  tikz-optics \
  tikz-page \
  tikz-palattice \
  tikz-qtree \
  tikz-relay \
  tikz-sfc \
  tikz-timing \
  tikzcodeblocks \
  tikzducks \
  tikzinclude \
  tikzmark \
  tikzorbital \
  tikzpagenodes \
  tikzpeople \
  tikzpfeile \
  tikzposter \
  tikzscale \
  tikzsymbols \
  timing-diagrams \
  tipa \
  tipfr \
  tkz-base \
  tkz-berge \
  tkz-doc \
  tkz-euclide \
  tkz-fct \
  tkz-graph \
  tkz-kiviat \
  tkz-linknodes \
  tkz-orm \
  tkz-tab \
  tools \
  tqft \
  translator \
  tsemlines \
  tufte-latex \
  typehtml \
  typewriter \
  ucharcat \
  ucharclasses \
  underscore \
  unicode-bidi \
  unicode-data \
  unicode-math \
  unisugar \
  updmap-map \
  upquote \
  url \
  venndiagram \
  visualpstricks \
  xcolor \
  xdvi \
  xdvi.x86_64-linux \
  xebaposter \
  xechangebar \
  xecjk \
  xecolor \
  xecyr \
  xeindex \
  xesearch \
  xespotcolor \
  xetex \
  xetex-itrans \
  xetex-pstricks \
  xetex-tibetan \
  xetex.x86_64-linux \
  xetexconfig \
  xetexfontinfo \
  xetexko \
  xevlna \
  xifthen \
  xkeyval \
  xltxtra \
  xpicture \
  xstring \
  xunicode \
  xypic

# Keep no backups (not required, simply makes cache bigger)
tlmgr option -- autobackup 0

# Update the TL install but add nothing new
tlmgr update --self --all --no-auto-install