# config/schedule.yml

register_webhooks:
  cron: "every day at 5"
  class: "TiiRegisterWebHookJob"

progress_turn_it_in_jobs:
  cron: "every 30 minutes"
  class: "TiiCheckProgressJob"

clean_up_auth_tokens:
  cron: "every 30 minutes"
  class: "ClearAccessTokensJob"

refresh_moderation_feedback_timestamps:
  cron: "every 60 minutes"
  class: "RefreshModerationFeedbackTimestampsJob"

aggregate_task_completion_stats:
  cron: "every day at 11:55pm"
  class: "AggregateTaskCompletionStatsJob"

# archive_old_units:
#   cron: "every 6 months"
#   class: "ArchiveOldUnitsJob"
