name: create-doubtfire-deployment
on:
  push:
    tags:
      - "v*"
    # branches:
    #   - '*.x'
    #   - 'development'
    #   - 'main'
  deployment:
  workflow_dispatch:
jobs:
  docker-deploy-development-image:
    if: github.repository_owner == 'doubtfire-lms'
    environment: doubtfire
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for development image
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: lmsdoubtfire/doubtfire-api
          tags: |
            type=semver,pattern={{major}}.{{minor}}.x-dev
      - name: Build and push api server
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-api-server:
    if: github.repository_owner == 'doubtfire-lms'
    environment: doubtfire
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v5
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for api server
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: lmsdoubtfire/apiServer
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern=prod-{{version}}
            type=semver,pattern=prod-{{major}}.{{minor}}
            type=semver,pattern=prod-{{major}}
      - name: Build and push api server
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: deployApi.Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-app-server:
    if: github.repository_owner == 'doubtfire-lms'
    environment: doubtfire
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for app server
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: lmsdoubtfire/appServer
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern=prod-{{version}}
            type=semver,pattern=prod-{{major}}.{{minor}}
            type=semver,pattern=prod-{{major}}
      - name: Build and push app server
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: deployAppSvr.Dockerfile
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
